# --- BAGIAN INI YANG HARUS DIUBAH ---
upstream nextjs_host {
    # SALAH (Ini menunjuk ke MacBook/Host):
    # server host.docker.internal:3000; 
    
    # BENAR (Ini menunjuk ke container 'app' via internal network Docker):
    server app:3000;
}
# ------------------------------------

upstream minio_internal {
    server minio:9000;
}

server {
    listen 80;
    server_name pemuda.magelangkota.go.id;
    client_max_body_size 20M;

    # Routing Gambar
    location /media/ {
        rewrite ^/media/(.*)$ /pemuda-uploads/$1 break;
        proxy_pass http://minio_internal;
        proxy_set_header Host $http_host;
    }

    # Routing Aplikasi Next.js
    location / {
        proxy_pass http://nextjs_host;
        
        # Header standar
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}