upstream nextjs_host {
    server app:3000;
}

upstream minio_internal {
    server minio:9000;
}

# Block 1: Redirect HTTP ke HTTPS (Wajib untuk Government Site)
server {
    listen 80;
    server_name pemuda.magelangkota.go.id;
    
    # Redirect semua request HTTP ke HTTPS
    return 301 https://$host$request_uri;
}

# Block 2: HTTPS Server
server {
    listen 443 ssl;
    server_name pemuda.magelangkota.go.id;

    # Konfigurasi SSL (Sesuaikan nama file sertifikat Anda)
    # File ini harus ada di folder ./certs yang dimount di docker-compose
    ssl_certificate     /etc/nginx/certs/fullchain.pem; 
    ssl_certificate_key /etc/nginx/certs/privkey.pem;
    
    # SSL Tuning (Best Practice)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 20M;

    # 1. Routing Gambar dengan CACHING
    location /media/ {
        rewrite ^/media/(.*)$ /pemuda-uploads/$1 break;
        proxy_pass http://minio_internal;
        proxy_set_header Host $http_host;

        # --- OPTIMASI CACHE ---
        # Cache gambar di browser user selama 30 hari
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
        
        # Hilangkan header MinIO yang tidak perlu diexpose ke publik
        proxy_hide_header x-amz-request-id;
        proxy_hide_header x-minio-deployment-id;
    }

    # 2. Routing Aplikasi Next.js
    location / {
        proxy_pass http://nextjs_host;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}