upstream nextjs_host {
    server app:3000;
}

upstream minio_internal {
    server minio:9000;
}

server {
    listen 80;
    server_name pemuda.magelangkota.go.id;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name pemuda.magelangkota.go.id;

    ssl_certificate     /etc/letsencrypt/live/pemuda.magelangkota.go.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pemuda.magelangkota.go.id/privkey.pem;
    
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    client_max_body_size 20M;

    # ==========================================
    # LOGIKA MAINTENANCE MODE
    # ==========================================
    
    # 1. Default: Maintenance Mati (0)
    set $maintenance_mode 0;

    # 2. Cek apakah file trigger 'maintenance.on' ada?
    if (-f /etc/nginx/maintenance_control/maintenance.on) {
        set $maintenance_mode 1;
    }

    # 3. Whitelist (Pengecualian)
    # Jika URL adalah halaman maintenance itu sendiri -> JANGAN REDIRECT
    if ($uri ~ ^/maintenance$) {
        set $maintenance_mode 0;
    }
    
    # Jika URL adalah asset Next.js (_next/static, dll) -> JANGAN REDIRECT
    # Agar styling/JS halaman maintenance tetap jalan
    if ($uri ~ ^/_next/) {
        set $maintenance_mode 0;
    }

    # Jika URL adalah asset gambar statis (/static/zhub.png) -> JANGAN REDIRECT
    if ($uri ~ ^/static/) {
        set $maintenance_mode 0;
    }

    # Jika URL adalah media/gambar dari MinIO -> JANGAN REDIRECT (Opsional, tergantung kebutuhan)
    if ($uri ~ ^/media/) {
        set $maintenance_mode 0;
    }

    # Jika URL adalah favicon -> JANGAN REDIRECT
    if ($uri ~ ^/favicon.ico) {
        set $maintenance_mode 0;
    }

    # 4. Eksekusi Redirect
    # Jika Mode Aktif (1) DAN bukan pengecualian di atas -> Lempar ke /maintenance
    if ($maintenance_mode = 1) {
        return 302 /maintenance;
    }
    # ==========================================

    # Routing Gambar
    location /media/ {
        rewrite ^/media/(.*)$ /pemuda-uploads/$1 break;
        proxy_pass http://minio_internal;
        proxy_set_header Host $http_host;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
        proxy_hide_header x-amz-request-id;
        proxy_hide_header x-minio-deployment-id;
    }

    # Routing Next.js
    location / {
        proxy_pass http://nextjs_host;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}